{{ config(materialized='view', schema='GOLD') }}

select
  doctor_id,
  specialty_type,
  specialty,
  total_consultations,
  unique_patients,
  active_days,
  unique_conditions_treated,
  walk_in_consults,
  scheduled_consults,
  successful_consults,
  patient_no_shows,
  pending_consults,
  success_rate_pct,
  no_show_rate_pct,
  avg_consults_per_day,
  repeat_patient_ratio,
  service_span_days,
  doctors_in_specialty,
  specialty_total_consults,
  specialty_unique_patients,
  avg_specialty_success_rate_pct,
  avg_specialty_no_show_rate_pct,
  performance_tier,
  workload_level,
  first_consultation,
  last_consultation,
  current_timestamp as load_timestamp
from {{ source('silver','doctor_benchmarked') }}
