version: 2

models:
  - name: aisql_med_consultations
    columns:
      - name: PATIENT_ID
        tests: [not_null]
      - name: DOCTOR_ID
        tests: [not_null]
      - name: SEVERITY
        tests:
          - accepted_values:
              values: ['High','Medium','Low']

  - name: vw_doctor_perf_scorecard
    columns:
      - name: DOCTOR_ID
        tests: [not_null]

  - name: healthcare_analyst_view
    columns:
      - name: PATIENT_ID
        tests: [not_null]
