USE ROLE ACCOUNTADMIN;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS BIH_DE_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + schemas
CREATE DATABASE IF NOT EXISTS BIHPOC;
CREATE SCHEMA IF NOT EXISTS BIHPOC.BRONZE;
CREATE SCHEMA IF NOT EXISTS BIHPOC.SILVER;
CREATE SCHEMA IF NOT EXISTS BIHPOC.GOLD;
CREATE SCHEMA IF NOT EXISTS BIHPOC.GOVERNANCE;

-- Role
CREATE ROLE IF NOT EXISTS BIH_DATA_ENGINEER;

-- Grants
GRANT USAGE ON WAREHOUSE BIH_DE_WH TO ROLE BIH_DATA_ENGINEER;

GRANT USAGE ON DATABASE BIHPOC TO ROLE BIH_DATA_ENGINEER;
GRANT USAGE ON SCHEMA BIHPOC.BRONZE TO ROLE BIH_DATA_ENGINEER;
GRANT USAGE ON SCHEMA BIHPOC.SILVER TO ROLE BIH_DATA_ENGINEER;
GRANT USAGE ON SCHEMA BIHPOC.GOLD TO ROLE BIH_DATA_ENGINEER;
GRANT USAGE ON SCHEMA BIHPOC.GOVERNANCE TO ROLE BIH_DATA_ENGINEER;

-- Allow creating objects in schemas (tables/views/stages/file formats)
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA BIHPOC.BRONZE TO ROLE BIH_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA BIHPOC.SILVER TO ROLE BIH_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA BIHPOC.GOLD TO ROLE BIH_DATA_ENGINEER;
GRANT CREATE VIEW
  ON SCHEMA BIHPOC.GOVERNANCE TO ROLE BIH_DATA_ENGINEER;

-- Assign role to your user and defaults
GRANT ROLE BIH_DATA_ENGINEER TO USER PUM;
ALTER USER PUM SET DEFAULT_ROLE = BIH_DATA_ENGINEER;
ALTER USER PUM SET DEFAULT_WAREHOUSE = BIH_DE_WH;