{% macro attach_data_quality_metrics() %}
  {% if var('enable_governance_hooks', false) %}
    {% set db = target.database %}
    {% set statements = [
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES'",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PATIENT_ID)",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (NAME)",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (AGE, AGE -> AGE > 5)",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (BLOOD_TYPE, BLOOD_TYPE -> BLOOD_TYPE in ('A+','A-','O-','B-','AB-','O+','AB+','B+'))",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS on (DATE_OF_ADMISSION)",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT on ()",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.MIN on (BILLING_AMOUNT)",
      "ALTER TABLE " ~ db ~ ".BRONZE.HEALTHCARE ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.AVG on (BILLING_AMOUNT)",
      "ALTER TABLE " ~ db ~ ".BRONZE.MEDICAL_CONSULTATIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES'",
      "CREATE OR REPLACE DATA METRIC FUNCTION " ~ db ~ ".GOVERNANCE.REFERENTIAL_CHECK(arg_t1 TABLE (arg_c1 STRING), arg_t2 TABLE (arg_c2 STRING)) RETURNS NUMBER AS 'SELECT COUNT(*) FROM arg_t1 WHERE arg_c1 NOT IN (SELECT arg_c2 FROM arg_t2)'",
      "ALTER TABLE " ~ db ~ ".BRONZE.MEDICAL_CONSULTATIONS ADD DATA METRIC FUNCTION " ~ db ~ ".GOVERNANCE.REFERENTIAL_CHECK ON (PATIENT_ID, TABLE (" ~ db ~ ".BRONZE.HEALTHCARE(PATIENT_ID)))",
      "ALTER TABLE " ~ db ~ ".BRONZE.MEDICAL_CONSULTATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PATIENT_ID)",
      "ALTER TABLE " ~ db ~ ".BRONZE.MEDICAL_CONSULTATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (DOCTOR_ID)",
      "ALTER TABLE " ~ db ~ ".BRONZE.MEDICAL_CONSULTATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT on ()"
    ] %}
    {% for sql in statements %}
      {% do run_query(sql) %}
    {% endfor %}
  {% else %}
    {{ log('enable_governance_hooks is false; skipping attach_data_quality_metrics', info=True) }}
  {% endif %}
{% endmacro %}
