-- Query history + login info (analysis)
SELECT DISTINCT
    qh.USER_NAME,
    qh.ROLE_NAME,
    qh.QUERY_TEXT,
    qh.QUERY_TYPE,
    qh.QUERY_ID,
    lh.CLIENT_IP,
    qh.START_TIME,
    qh.END_TIME,
    qh.EXECUTION_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh
JOIN SNOWFLAKE.ACCOUNT_USAGE.SESSIONS s ON qh.SESSION_ID = s.SESSION_ID
JOIN SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY lh ON s.LOGIN_EVENT_ID = lh.EVENT_ID;
